spring.application.name=condo-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/condoadmin
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.secretkey: "uwdjqwijj129d01j0d91j29d0j1id89fd"
spring.emissor: "gabrielvieira"
spring.tempoExpiracao: 30